name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to Homelab"
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Connect to Cloudflare Tunnel
        run: |
          nohup cloudflared tunnel --no-autoupdate run --token ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }} &
          sleep 10  # Give cloudflared time to establish the connection

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-homelab
            HostName $SSH_HOSTNAME
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
            ProxyCommand cloudflared access ssh --hostname %h
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}

      - name: Deploy site
        id: deploySite
        run: ssh my-homelab "~/redeploy-site.sh"

      - name: Docker status
        run: ssh my-homelab "docker ps"

      - name: Cleanup
        if: always()
        run: killall cloudflared